#/bin/bash
echo "run apt update and apt upgrade"
echo "run apt update and apt upgrade"
echo "run apt update and apt upgrade"
echo "run apt update and apt upgrade"
echo "run apt update and apt upgrade"
echo "run apt update and apt upgrade"
echo "run apt update and apt upgrade"
echo "run apt update and apt upgrade"
echo "run apt update and apt upgrade"
sudo apt update && sudo apt upgrade -y
echo "step 1 done"
echo "step 1 done"
echo "step 1 done"
echo "step 1 done"
echo "step 1 done"
echo "step 1 done"
echo "step 1 done"
echo "Installing bgtools"
echo "Installing bgtools"
echo "Installing bgtools"
echo "Installing bgtools"
echo "Installing bgtools"
echo "Installing bgtools"
echo "Installing bgtools"
echo "Installing bgtools"
echo "Installing bgtools"
echo "Installing bgtools"
bash -c "$(curl -sSL https://artifactory.berkshiregrey.com/artifactory/generic-local/bg_tools/setup-developer/linux/setup-developer)"
echo "bgtools installed"
echo "bgtools installed"
echo "bgtools installed"
echo "bgtools installed"
echo "bgtools installed"
echo "bgtools installed"
echo "bgtools installed"
echo "bgtools installed"
echo "bgtools installed"
echo "bgtools installed"
echo "Installing devbox"
echo "Installing devbox"
echo "Installing devbox"
echo "Installing devbox"
echo "Installing devbox"
echo "Installing devbox"
echo "Installing devbox"
echo "Installing devbox"
echo "Installing devbox"
echo "Installing devbox"
echo "Installing devbox"
echo "Installing devbox"
bgtool deps install devbox
echo "devbox installed"
echo "devbox installed"
echo "devbox installed"
echo "devbox installed"
echo "devbox installed"
echo "devbox installed"
echo "devbox installed"
echo "devbox installed"
echo "devbox installed"
echo "devbox installed"
echo "devbox installed"
echo "creating workspace"
echo "creating workspace"
echo "creating workspace"
echo "creating workspace"
echo "creating workspace"
echo "creating workspace"
echo "creating workspace"
echo "creating workspace"
echo "creating workspace"
echo "creating workspace"
echo "creating workspace"
echo "creating workspace"
bgtool ws create fuji-smalls -w ~/devel/ros_ws
echo "copy swiftdecoder files"
echo "copy swiftdecoder files"
echo "copy swiftdecoder files"
echo "copy swiftdecoder files"
echo "copy swiftdecoder files"
echo "copy swiftdecoder files"
echo "copy swiftdecoder files"
sudo rsync -av /home/robot/5.2.17/5.2.17 /usr/local/swiftdecoder/
sudo chmod -R 644 /usr/local/swiftdecoder/
echo "done"
echo "done"
echo "done"
echo "done"
echo "done"
echo "done"
#echo "build source codes"
#cd ~/devel/ros_ws
#catkin build hyper_scanner
#echo" source the environment"
#source ./devel/setup.bash
#echo "run the app"
#./devel/lib/hyper_scanner/bg_scanner_main ./src/bg_customer/customer_systems/systems/fuji_frankensystem/config/hyperscanner.yaml
