---
# tasks file for hyperscanner
#
#

#- name: Copy netplan configuration files
#  copy:
#      src: files/01-netcfg.yaml
#      dest: "/etc/netplan/01-netcfg.yaml"
#      owner: root
#      group: root
#      mode: 0644
#      backup: yes

- name: Copy grub files to make changes for USB cameras
  copy:
      src: files/grub
      dest: "/etc/default/grub"
      owner: root
      group: root
      mode: 0644
      backup: yes

- name: Copy the swiftdecoder lib files
  copy:
     src: files/5.2.17
     dest: "/home/robot/5.2.17"
     owner: root
     group: root
     mode: 644

- name: Update the grub config
  shell: update-grub

- name: copy the bgtools install script
  copy:
      src: files/install_bgtools.sh
      dest: "/home/robot/bgtools_install.sh"
      owner: robot
      group: robot
      mode: 755

- name: Execute the script
  local_action: sh /home/robot/bgtools_install.sh
