---
# tasks file for hyperscanner
#
#

- name: Copy netplan configuration files
  copy:
      src: files/01-netcfg.yaml
      dest: "/etc/netplan/01-netcfg.yaml"
      owner: root
      group: root
      mode: 0644
      backup: yes

      #- name : run a netplan apply
      # shell: netplan apply

- name: Copy grub files to make changes for USB cameras
  copy:
      src: files/grub
      dest: "/etc/default/grub"
      owner: root
      group: root
      mode: 0644
      backup: yes

- name: Copy the swiftdecoder lib files
  copy:
     src: files/5.2.17
     dest: "/tmp/5.2.17"
     owner: root
     group: root
     mode: 755

- name: Update the grub config
  shell: update-grub

- name: copy the bgtools install script
  copy:
      src: files/bgtools_install.sh
      dest: "/tmp/bgtools_install.sh"
      owner: robot
      group: robot
      mode: 755
